version: 2
jobs:

  build:
    working_directory: ~/home/crownstack/helpcodes/CircleCIDemo
    

   machine:
    environment:
      ANDROID_HOME: /usr/local/android-sdk-linux
      JVM_OPTS: -Xmx3200m

    general:
        artifacts:
            - /home/ubuntu/resume-manager/app/build/outputs/apk/
      
    steps:
      - checkout

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Run Tests
          command: ./gradlew lint test

      - store_artifacts:
          path: app/build/reports
          destination: reports

      - store_test_results:
          path: app/build/test-results


    test:
      override:
        - ./gradlew assembleRelease
        - cp -r CircleCIDemo/build/outputs $CIRCLE_ARTIFACTS
