version: 2
jobs:
  build:
    working_directory: ~/home/crownstack/helpcodes/CircleCIDemo/

    machine:
        java:
            version: oraclejdk8
        environment:
            ANDROID_HOME: /home/crownstack/AndroidStudioIDE/Sdk
            JVM_OPTS: -Xmx3200

    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew app:dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
