version: 2
jobs:

  build:
    working_directory: ~/home/crownstack/helpcodes/CircleCIDemo

    general:
        artifacts:
            - /home/ubuntu/AndroidCI/app/build/outputs/apk/

    machine:
        environment:
        ANDROID_HOME: /usr/local/android-sdk-linux
        JVM_OPTS: -Xmx3200m



    dependencies:
        pre:
           ./gradlew androidDependencies


    test:
        override:
            - ./gradlew assemble
    - cp -r app/build/outputs $CIRCLE_ARTIFACTS

